version: "3"
services:
  nginx:
    ports:
      - "4545:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development

    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - SESSION_SECRET=banana
    command: yarn dev
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
