version: "3"
services:
  node-app:
    build: .
    ports:
      - "4545:4545"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=4545
    # env_file:
    #   - ./.envs
